apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.api.name }}-nodeport"
spec:
  selector:
    app: {{ .Release.name }}
    component: {{ .Values.api.name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.general.ports.api.api.port }}
      targetPort: {{ .Values.general.ports.api.api.port }}
