apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.locust.name }}-nodeport"
spec:
  selector:
    app: {{ .Release.name }}
    component: {{ .Values.locust.name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.general.ports.locust.web.port }}
      targetPort: {{ .Values.general.ports.locust.web.port }}
